Team-SIGNAL/SIGNAL-ANDROID

domain/src/main/kotlin/com/signal/domain/enums/Gender.kt, presentation/build.gradle.kts, presentation/src/main/java/com/signal/signal_android/SignalApp.kt, presentation/src/main/java/com/signal/signal_android/designsystem/component/SignUpTitle.kt, presentation/src/main/java/com/signal/signal_android/designsystem/radiobutton/SignalRadioButton.kt, presentation/src/main/java/com/signal/signal_android/feature/landing/Landing.kt, presentation/src/main/java/com/signal/signal_android/feature/signin/SignIn.kt, presentation/src/main/java/com/signal/signal_android/feature/signup/SignUpAccount.kt, presentation/src/main/java/com/signal/signal_android/feature/signup/SignUpUser.kt, presentation/src/main/java/com/signal/signal_android/navigation/AuthNavigation.kt, presentation/src/main/java/com/signal/signal_android/navigation/NavigationRoute.kt, presentation/src/main/java/com/signal/signal_android/navigation/UserNavigation.kt, presentation/src/main/res/values/strings.xml
> 회원가입 퍼블리싱을 진행하였습니다.
- SignUpUser 퍼블리싱
- SignUpAccount 퍼블리싱
- SignUp navigation 연결
- SignUpTitle component
=> 🔀 :: (#8) 회원가입 퍼블리싱

.github/workflows/android.yml
=> 🔀 :: (#15) ci 구축

data/src/main/kotlin/com/signal/data/api/SignalUrl.kt, data/src/main/kotlin/com/signal/data/api/UserApi.kt, data/src/main/kotlin/com/signal/data/datasource/user/remote/RemoteUserDataSource.kt, data/src/main/kotlin/com/signal/data/datasource/user/remote/RemoteUserDataSourceImpl.kt, data/src/main/kotlin/com/signal/data/model/signup/SignUpRequest.kt, data/src/main/kotlin/com/signal/data/repository/UserRepositoryImpl.kt, domain/src/main/java/com/signal/signal_android/domain/regex/Regexs.kt, domain/src/main/kotlin/com/signal/domain/repository/UserRepository.kt, domain/src/main/kotlin/com/signal/domain/usecase/users/SignInUseCase.kt, domain/src/main/kotlin/com/signal/domain/usecase/users/SignUpUseCase.kt, presentation/src/main/java/com/signal/signal_android/SignalApplication.kt, presentation/src/main/java/com/signal/signal_android/designsystem/textfield/SignalTextField.kt, presentation/src/main/java/com/signal/signal_android/feature/signin/SignIn.kt, presentation/src/main/java/com/signal/signal_android/feature/signup/SignUpAccount.kt, presentation/src/main/java/com/signal/signal_android/feature/signup/SignUpSideEffect.kt, presentation/src/main/java/com/signal/signal_android/feature/signup/SignUpState.kt, presentation/src/main/java/com/signal/signal_android/feature/signup/SignUpUser.kt, presentation/src/main/java/com/signal/signal_android/feature/signup/SignUpViewModel.kt, presentation/src/main/java/com/signal/signal_android/navigation/AuthNavigation.kt, presentation/src/main/java/com/signal/signal_android/viewmodel/BaseViewModel.kt, presentation/src/main/java/com/signal/signal_android/viewmodel/SignInViewModel.kt, presentation/src/main/res/drawable/ic_calendar.xml, presentation/src/main/res/values/strings.xml
> 회원가입 서버 연동 로직을 작성했습니다.
- module 별 코드 작성
=> 🔀 :: (#14) 회원가입 서버 연동

presentation/build.gradle.kts, presentation/src/main/AndroidManifest.xml, presentation/src/main/java/com/signal/signal_android/MainActivity.kt, presentation/src/main/java/com/signal/signal_android/SignalApp.kt, presentation/src/main/java/com/signal/signal_android/designsystem/button/BasicButton.kt, presentation/src/main/java/com/signal/signal_android/designsystem/component/Header.kt, presentation/src/main/java/com/signal/signal_android/designsystem/component/SignalDialog.kt, presentation/src/main/java/com/signal/signal_android/designsystem/textfield/SignalTextField.kt, presentation/src/main/java/com/signal/signal_android/feature/main/Main.kt, presentation/src/main/java/com/signal/signal_android/feature/main/feed/CommentDialog.kt, presentation/src/main/java/com/signal/signal_android/feature/main/feed/Feed.kt, presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedDetails.kt, presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPage.kt, presentation/src/main/java/com/signal/signal_android/navigation/MainNavigation.kt, presentation/src/main/java/com/signal/signal_android/navigation/NavigationRoute.kt, presentation/src/main/res/drawable/ic_back.xml, presentation/src/main/res/drawable/ic_edit.xml, presentation/src/main/res/drawable/ic_more.xml, presentation/src/main/res/values/strings.xml
> 커뮤니티 목록, 상세보기, 댓글 페이지를 퍼블리싱 했습니다.
- 커뮤니티 목록, 상세보기 및 댓글 퍼블리싱
- 모달 컴포넌트화
- 댓글 바텀 시트 구현
=> 🔗 :: (#28) 커뮤니티 퍼블리싱

presentation/src/main/java/com/signal/signal_android/BaseViewModel.kt, presentation/src/main/java/com/signal/signal_android/SignalApplication.kt, presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPageViewModel.kt, presentation/src/main/java/com/signal/signal_android/feature/signin/SignIn.kt, presentation/src/main/java/com/signal/signal_android/feature/signin/SignInViewModel.kt, presentation/src/main/java/com/signal/signal_android/feature/signup/SignUpViewModel.kt
> SignInViewModel, BaseViewModel 패키지 이동
- viewmodel 패키지 제거
- view model feature 패키지 내부로 이동
=> 🔀 :: (#26) viewmodel 패키지 이동

data/src/main/kotlin/com/signal/data/api/SignalUrl.kt, data/src/main/kotlin/com/signal/data/api/UserApi.kt, data/src/main/kotlin/com/signal/data/datasource/user/remote/RemoteUserDataSource.kt, data/src/main/kotlin/com/signal/data/datasource/user/remote/RemoteUserDataSourceImpl.kt, data/src/main/kotlin/com/signal/data/model/mypage/FetchUserInformationResponse.kt, data/src/main/kotlin/com/signal/data/repository/UserRepositoryImpl.kt, domain/src/main/kotlin/com/signal/domain/repository/UserRepository.kt, domain/src/main/kotlin/com/signal/domain/usecase/users/FetchUserInformationUseCase.kt, presentation/src/main/java/com/signal/signal_android/SignalApp.kt, presentation/src/main/java/com/signal/signal_android/SignalApplication.kt, presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPage.kt, presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPageState.kt, presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPageViewModel.kt, presentation/src/main/res/values/strings.xml
> 마이페이지 내 정보 조회를 구현했습니다.
- 마이페이지 내 정보 조회 구현
=> 🔀 :: (#20) 마이페이지 내 정보 조회 기능 구현

presentation/src/main/java/com/signal/signal_android/SignalApp.kt, presentation/src/main/java/com/signal/signal_android/designsystem/dropdown/SignalDropDown.kt, presentation/src/main/java/com/signal/signal_android/feature/main/Main.kt, presentation/src/main/java/com/signal/signal_android/feature/main/feed/Feed.kt, presentation/src/main/java/com/signal/signal_android/feature/main/feed/Report.kt, presentation/src/main/java/com/signal/signal_android/navigation/MainNavigation.kt, presentation/src/main/java/com/signal/signal_android/navigation/NavigationRoute.kt, presentation/src/main/res/drawable/ic_down.xml, presentation/src/main/res/values/strings.xml
> 커뮤니티 신고 페이지를 퍼블리싱 했습니다.
- 드롭다운 디자인시스템 구현
- Report 퍼블리싱
=> 🔀 :: (#36) 커뮤니티 신고 퍼블리싱

presentation/build.gradle.kts, presentation/src/main/java/com/signal/signal_android/feature/main/home/Home.kt, presentation/src/main/res/values/strings.xml
> 홈 스크린 퍼블리싱 작업을 진행했습니다.
- vice chart 라이브러리 의존성 추가
- 홈 스크린 퍼블리싱
=> 🔀 :: (#27) 홈 퍼블리싱

data/src/main/kotlin/com/signal/data/util/TokenInterceptor.kt
=> 🔀 :: (#43) 토큰 bearer 추가

presentation/src/main/java/com/signal/signal_android/MainActivity.kt, presentation/src/main/java/com/signal/signal_android/SignalApp.kt, presentation/src/main/java/com/signal/signal_android/feature/signin/SignInViewModel.kt, presentation/src/main/res/values/strings.xml
> navigation 로직 버그 수정
- 뒤로가기 두 번 이벤트 추가
- navigation popup 추가
=> 🔀 :: (#46) navigation 로직 버그 수정

data/src/main/kotlin/com/signal/data/api/UserApi.kt, presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPageViewModel.kt
> 회원탈퇴 로직을 수정했습니다.
- userApi에 suspend 추가
=> 🔀 :: (#45) 회원탈퇴 로직 수정

data/src/main/kotlin/com/signal/data/model/mypage/FetchUserInformationResponse.kt, data/src/main/kotlin/com/signal/data/repository/UserRepositoryImpl.kt, domain/src/main/kotlin/com/signal/domain/entity/UserInformationEntity.kt, domain/src/main/kotlin/com/signal/domain/repository/UserRepository.kt, presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPage.kt, presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPageState.kt, presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPageViewModel.kt
> 마이페이지 내 정보 조회 수정을 했습니다.
- entity mapping 함수 구현
- 변수 타입 변경
- 변수명 변경
=> 🔀 :: (#51) 마이페이지 내 정보 조회 수정

data/build.gradle.kts, data/src/main/kotlin/com/signal/data/dao/DiagnosisDao.kt, data/src/main/kotlin/com/signal/data/database/SignalDatabase.kt, data/src/main/kotlin/com/signal/data/model/diagnosis/DiagnosisEntity.kt, domain/build.gradle.kts, presentation/build.gradle.kts, presentation/src/main/java/com/signal/signal_android/DBInitializer.kt, presentation/src/main/java/com/signal/signal_android/MainActivity.kt, presentation/src/main/res/values/strings.xml
=> 🔀 :: (#58) room 세팅

presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPage.kt, presentation/src/main/res/values/strings.xml
> 마이페이지 뷰 수정을 합니다.
- ripple 효과를 추가했습니다.
- elevation 수정했습니다.
- dialog 추가했습니다.
=> 🔀 :: (#65) 마이페이지 뷰 수정

presentation/src/main/java/com/signal/signal_android/feature/diagnosis/Diagnosis.kt, presentation/src/main/res/values/strings.xml
=> 🔀 :: (#68) 자가진단 설문 수정

data/src/main/kotlin/com/signal/data/api/FeedApi.kt, data/src/main/kotlin/com/signal/data/api/SignalUrl.kt, data/src/main/kotlin/com/signal/data/datasource/feed/FeedDataSource.kt, data/src/main/kotlin/com/signal/data/datasource/feed/FeedDataSourceImpl.kt, data/src/main/kotlin/com/signal/data/model/feed/response/FetchPostsResponse.kt, data/src/main/kotlin/com/signal/data/repository/FeedRepositoryImpl.kt, domain/src/main/kotlin/com/signal/domain/entity/PostsEntity.kt, domain/src/main/kotlin/com/signal/domain/repository/FeedRepository.kt, presentation/src/main/java/com/signal/signal_android/feature/main/feed/Feed.kt, presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedDetails.kt, presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedViewModel.kt
=> 🔀 :: (#77) 피드 삭제 구현

data/src/main/kotlin/com/signal/data/api/SignalUrl.kt, data/src/main/kotlin/com/signal/data/model/feed/response/FetchPostDetailsResponse.kt, domain/src/main/kotlin/com/signal/domain/entity/PostDetailsEntity.kt, presentation/src/main/java/com/signal/signal_android/feature/main/feed/Feed.kt, presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedDetails.kt, presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedState.kt, presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedViewModel.kt
> 상세보기 명세를 수정했습니다.
- 상세보기 명세 수정
=> 🔀 :: (#97) 상세보기 명세 수정

data/src/main/kotlin/com/signal/data/api/SignalUrl.kt, data/src/main/kotlin/com/signal/data/model/feed/request/CreatePostRequest.kt, data/src/main/kotlin/com/signal/data/repository/FeedRepositoryImpl.kt, domain/src/main/kotlin/com/signal/domain/repository/FeedRepository.kt, presentation/src/main/java/com/signal/signal_android/feature/main/feed/Feed.kt, presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedState.kt, presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedViewModel.kt
> 피드 조회 상태 로직을 리팩토링 했습니다.
- 삭제 후 바로 리스트에 반영
- 작성 후 바로 리스트에 반영
=> 🔀 :: (#94) 피드 조회 리팩토링

data/src/main/kotlin/com/signal/data/api/FeedApi.kt, data/src/main/kotlin/com/signal/data/datasource/feed/FeedDataSource.kt, data/src/main/kotlin/com/signal/data/datasource/feed/FeedDataSourceImpl.kt, data/src/main/kotlin/com/signal/data/repository/FeedRepositoryImpl.kt, domain/src/main/kotlin/com/signal/domain/repository/FeedRepository.kt, presentation/src/main/java/com/signal/signal_android/SignalApp.kt, presentation/src/main/java/com/signal/signal_android/feature/main/Main.kt, presentation/src/main/java/com/signal/signal_android/feature/main/feed/CreatePost.kt, presentation/src/main/java/com/signal/signal_android/feature/main/feed/Feed.kt, presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedState.kt, presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedViewModel.kt, presentation/src/main/java/com/signal/signal_android/navigation/MainNavigation.kt, presentation/src/main/java/com/signal/signal_android/navigation/NavigationRoute.kt, presentation/src/main/res/values/strings.xml
> 피드 수정 기능을 구현했습니다.
- 비즈니스 로직 작성
- 작성 예외 처리
=> 🔀 :: (#76) 피드 수정 구현

presentation/src/main/java/com/signal/signal_android/feature/main/home/Home.kt, presentation/src/main/res/values/strings.xml
> 우울증 그래프 초기 설정 작업을 진행하였습니다.
- 데이터 부족 텍스트 추가
=> 🔀 :: (#103) 우울증 그래프 초기 설정

presentation/src/main/java/com/signal/signal_android/feature/main/feed/Feed.kt, presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedDetails.kt, presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedSideEffect.kt, presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedViewModel.kt, presentation/src/main/java/com/signal/signal_android/navigation/MainNavigation.kt
> 게시글 상세보기에서 수정 기능과 삭제 기능을 구현했습니다.
- 상세보기에서 수정, 삭제 구현
=> 🔀 :: (#105) 게시글 상세에서 수정, 삭제 기능 구현

presentation/src/main/java/com/signal/signal_android/feature/main/feed/CreatePost.kt, presentation/src/main/java/com/signal/signal_android/feature/main/feed/Feed.kt, presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedState.kt, presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedViewModel.kt
> 피드 페이징을 구현했습니다.
- 페이징 구현
- 피드 게시글 내용 길이 제한 증가 100 -> 300
=> 🔀 :: (#74) 피드 페이징 구현

presentation/src/main/java/com/signal/signal_android/feature/main/home/Home.kt
> 그래프 색상을 변경했습니다.
- 그래프 색상 변경
죽을뻔했어요
=> 🔀 :: (#92) 그래프 색상 변경

data/build.gradle.kts, data/src/main/kotlin/com/signal/data/dao/MyPageDao.kt, data/src/main/kotlin/com/signal/data/database/SignalDatabase.kt, data/src/main/kotlin/com/signal/data/datasource/user/local/LocalUserDataSource.kt, data/src/main/kotlin/com/signal/data/datasource/user/local/LocalUserDataSourceImpl.kt, data/src/main/kotlin/com/signal/data/model/mypage/FamousSayingModel.kt, data/src/main/kotlin/com/signal/data/repository/UserRepositoryImpl.kt, domain/src/main/kotlin/com/signal/domain/entity/FamousSayingEntity.kt, domain/src/main/kotlin/com/signal/domain/repository/UserRepository.kt, domain/src/main/kotlin/com/signal/domain/usecase/users/AddFamousSayingUseCase.kt, domain/src/main/kotlin/com/signal/domain/usecase/users/GetFamousSayingUseCase.kt, presentation/build.gradle.kts, presentation/src/main/java/com/signal/signal_android/DBInitializer.kt, presentation/src/main/java/com/signal/signal_android/SignalApplication.kt, presentation/src/main/java/com/signal/signal_android/feature/main/Main.kt, presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPage.kt, presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPageState.kt, presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPageViewModel.kt, presentation/src/main/res/values/strings.xml
> 명언 기능을 구현했습니다.
- 명언 저장, 불러오기 로직 구현
=> 🔀 :: (#93) 명언 기능 구현

data/src/main/kotlin/com/signal/data/api/RecommendApi.kt, data/src/main/kotlin/com/signal/data/api/SignalUrl.kt, data/src/main/kotlin/com/signal/data/datasource/recommend/RecommendDataSource.kt, data/src/main/kotlin/com/signal/data/datasource/recommend/RecommendDataSourceImpl.kt, data/src/main/kotlin/com/signal/data/model/recommend/FetchRecommendDetailsResponse.kt, data/src/main/kotlin/com/signal/data/model/recommend/FetchRecommendsResponse.kt, data/src/main/kotlin/com/signal/data/repository/RecommendRepositoryImpl.kt, domain/src/main/kotlin/com/signal/domain/entity/RecommendDetailsEntity.kt, domain/src/main/kotlin/com/signal/domain/entity/RecommendsEntity.kt, domain/src/main/kotlin/com/signal/domain/repository/RecommendRepository.kt, presentation/src/main/java/com/signal/signal_android/feature/main/diary/AllDiary.kt, presentation/src/main/java/com/signal/signal_android/feature/main/recommend/Recommend.kt, presentation/src/main/java/com/signal/signal_android/feature/main/recommend/RecommendDetails.kt, presentation/src/main/java/com/signal/signal_android/feature/main/recommend/RecommendState.kt, presentation/src/main/java/com/signal/signal_android/feature/main/recommend/RecommendViewModel.kt, presentation/src/main/java/com/signal/signal_android/feature/main/recommend/Recommends.kt, presentation/src/main/res/values/strings.xml
> 추천 상세보기 기능을 구현했습니다.
- 추천 목록에서 url intent 기능 구현
- 추천 상세 퍼블리싱 및 url intent 기능 구현
=> 🔀 :: (#121) 추천 상세보기 기능 구현

data/src/main/kotlin/com/signal/data/dao/MyPageDao.kt, data/src/main/kotlin/com/signal/data/database/SignalDatabase.kt, data/src/main/kotlin/com/signal/data/datasource/user/local/LocalUserDataSource.kt, data/src/main/kotlin/com/signal/data/datasource/user/local/LocalUserDataSourceImpl.kt, data/src/main/kotlin/com/signal/data/model/mypage/UserInformationModel.kt, data/src/main/kotlin/com/signal/data/repository/UserRepositoryImpl.kt, domain/src/main/kotlin/com/signal/domain/repository/UserRepository.kt, domain/src/main/kotlin/com/signal/domain/usecase/users/GetUserInformationUseCase.kt, domain/src/main/kotlin/com/signal/domain/usecase/users/SetUserInformationUseCase.kt, domain/src/main/kotlin/com/signal/domain/usecase/users/UpdateUserInformationUseCase.kt, presentation/src/main/java/com/signal/signal_android/SignalApplication.kt, presentation/src/main/java/com/signal/signal_android/feature/main/home/Home.kt, presentation/src/main/java/com/signal/signal_android/feature/main/home/HomeState.kt, presentation/src/main/java/com/signal/signal_android/feature/main/home/HomeViewModel.kt, presentation/src/main/java/com/signal/signal_android/feature/main/mypage/MyPage.kt, presentation/src/main/java/com/signal/signal_android/feature/main/mypage/MyPageViewModel.kt
> 마이페이지 정보를 로컬에 저장하는 기능을 구현했습니다.
- Home user profile image 불러오기 로직 구현
- Room 로직 구현
=> 🔀 :: (#123) 마이페이지 로컬 정보 저장 기능 구현

data/src/main/kotlin/com/signal/data/model/recommend/FetchRecommendsResponse.kt, domain/src/main/kotlin/com/signal/domain/entity/RecommendsEntity.kt, presentation/src/main/java/com/signal/signal_android/feature/main/recommend/RecommendDetails.kt
> 추천 이미지 항목 중 이미지에 대한 옵셔널 작업을 수행하였습니다.
- 이미지 옵셔널
- 추천 상세 버튼 위치 수정
=> 🔀 :: (#129) 추천 이미지 옵셔널 처리

presentation/src/main/java/com/signal/signal_android/feature/main/mypage/MyPage.kt, presentation/src/main/res/values/strings.xml
> 아직 달성한 업적이 없는 경우 뷰에 텍스트를 표시하는 기능을 구현하였습니다.
- text 구현
=> 🔀 :: (#136) 업적 수정

data/src/main/kotlin/com/signal/data/api/SignalUrl.kt, data/src/main/kotlin/com/signal/data/api/UserApi.kt, data/src/main/kotlin/com/signal/data/datasource/user/remote/RemoteUserDataSource.kt, data/src/main/kotlin/com/signal/data/datasource/user/remote/RemoteUserDataSourceImpl.kt, data/src/main/kotlin/com/signal/data/model/mypage/EditProfileRequest.kt, data/src/main/kotlin/com/signal/data/repository/UserRepositoryImpl.kt, domain/src/main/kotlin/com/signal/domain/repository/UserRepository.kt, presentation/src/main/java/com/signal/signal_android/SignalApp.kt, presentation/src/main/java/com/signal/signal_android/SignalApplication.kt, presentation/src/main/java/com/signal/signal_android/feature/main/Main.kt, presentation/src/main/java/com/signal/signal_android/feature/main/mypage/EditProfile.kt, presentation/src/main/java/com/signal/signal_android/feature/main/mypage/MyPage.kt, presentation/src/main/java/com/signal/signal_android/feature/main/mypage/MyPageSideEffect.kt, presentation/src/main/java/com/signal/signal_android/feature/main/mypage/MyPageViewModel.kt, presentation/src/main/java/com/signal/signal_android/navigation/MainNavigation.kt, presentation/src/main/java/com/signal/signal_android/navigation/NavigationRoute.kt, presentation/src/main/res/values/strings.xml
> 프로필 사진 수정 기능을 구현합니다.
- 프로필 사진 수정 스크린 구현
- 프로필 사진 수정 기능 구현
=>  🔀 :: (#83) 프로필 사진 수정 기능 구현 

presentation/src/main/java/com/signal/signal_android/feature/reservation/Reservation.kt, presentation/src/main/java/com/signal/signal_android/feature/reservation/ReservationState.kt, presentation/src/main/java/com/signal/signal_android/feature/reservation/ReservationViewModel.kt
> 병원 진료 예약 코드 리팩토링을 진행했습니다.
- list 로직 변경
=> 🔀 :: (#141) 병원 진료 예약 코드 리팩토링

presentation/src/main/java/com/signal/signal_android/feature/main/diary/AllDiary.kt, presentation/src/main/java/com/signal/signal_android/feature/main/diary/CreateDiary.kt, presentation/src/main/java/com/signal/signal_android/feature/main/diary/DiaryState.kt, presentation/src/main/java/com/signal/signal_android/feature/main/diary/DiaryViewModel.kt, presentation/src/main/java/com/signal/signal_android/feature/main/feed/CommentDialog.kt, presentation/src/main/java/com/signal/signal_android/feature/main/home/Home.kt, presentation/src/main/java/com/signal/signal_android/feature/main/mypage/MyPage.kt
> qa 해서 나온 버그를 수정합니다.
- Diary 상태 업데이트
- Profile Crop 수정
=> 🔀 :: (#145) qa 버그

presentation/src/main/java/com/signal/signal_android/feature/main/recommend/Recommend.kt, presentation/src/main/java/com/signal/signal_android/feature/main/recommend/Recommends.kt, presentation/src/main/java/com/signal/signal_android/navigation/MainNavigation.kt, presentation/src/main/java/com/signal/signal_android/navigation/NavigationRoute.kt, presentation/src/main/res/values/strings.xml
> 카테고리가 고정되는 버그를 수정했습니다.
- navArgument name 변경
- 병원 내원하기 -> 취미 가져보기 변경
=> 🔀 :: (#150) 추천 카테고리 로직 버그 수정

presentation/src/main/java/com/signal/signal_android/feature/main/feed/Feed.kt, presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedDetails.kt, presentation/src/main/java/com/signal/signal_android/feature/main/mypage/EditProfile.kt
> 피드 검색 아이콘을 제거했습니다.
- feed Header trailing Icon 제거
=> 🔀 :: (#154) 검색 기능 삭제

presentation/src/main/java/com/signal/signal_android/designsystem/foundation/SignalColor.kt, presentation/src/main/java/com/signal/signal_android/feature/main/diary/Diary.kt, presentation/src/main/java/com/signal/signal_android/feature/main/home/Home.kt, presentation/src/main/res/values/strings.xml
> 우울증 수치 정보를 구현합니다.
- 우울증 수치 정보 Dialog 구현
- Diary 수정
=> 🔀 :: (#156) 우울증 수치 정보 구현 
